language: python
python:
  - "3.7"
install:
  - pip install django
  - pip install django-nose
  - pip install selenium
  - pip install coverage
script:
  - python3 manage.py makemigrations
  - python3 manage.py migrate
  - ./manage.py test --with-coverage
