language: python
python:
  - "3.7"
install:
  - pip install django
  - pip install django-nose
  - pip install crispy-forms
  - pip install selenium
  - pip install coverage
script:
  - python3 runn/manage.py makemigrations
  - python3 runn/manage.py migrate
  - ./runn/manage.py test --with-coverage
