before script:
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/
  - export CHROME_BIN=chromium-browser
language: python
python:
  - "3.7"
install:
  - pip install django
  - pip install django-nose
  - pip install selenium
  - pip install coverage
script:
  - 
