language: python
python:
  - "3.7"
install:
  - pip install django
  - pip install django-nose
  - pip install django-crispy-forms
  - pip install selenium
  - pip install coverage
before_script:
  - python3 runn/manage.py runserver &
script:
  - python3 runn/manage.py makemigrations
  - python3 runn/manage.py migrate
  - touch runn/.coveragerc
  - echo
    "[run]
      omit =
      *\manage.py
      *\xml\sax\expatreader.py
      *\xml\dom\pulldom.py
      *\django\*

    [report]
      omit =
      *\manage.py
      *\xml\sax\expatreader.py
      *\xml\dom\pulldom.py
      *\django\*" >> runn/.coveragerc

  - ./runn/manage.py test main --with-coverage
