language: python
python:
  - "3.7"
install:
  - pip install django
  - pip install django-nose
  - pip install django-crispy-forms
  - pip install selenium
  - pip install codecov
before_script:
  - python3 runn/manage.py runserver &
script:
  - python3 runn/manage.py makemigrations
  - python3 runn/manage.py migrate
  - coverage run runn/main/tests.py
after_success:
  - codecov
