# Generated by Django 3.0.3 on 2020-02-20 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.contrib.auth.models import User

# def create_profiles(apps, schema_editor):
#     for i in range(5):
#         user = User.objects.create_user(
#         username = 'nancy',
#         password = 'opensesame',
#         email = 'nancy@nancy.com')
#         user.save( )

#         profile = Profile

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(default='', max_length=50)),
                ('last_name', models.TextField(default='', max_length=50)),
                ('email', models.TextField(blank=True, max_length=75)),
                ('tagline', models.TextField(blank=True, max_length=250)),
                ('location', models.TextField(blank=True, max_length=100)),
                ('user_type', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('run_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(default='title holder.', max_length=100)),
                ('distance', models.FloatField(default=0.0)),
                ('time', models.IntegerField(default=0)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.TextField(default='', max_length=100)),
                ('image', models.TextField(blank=True, max_length=250)),
                ('content', models.TextField(blank=True, default='', max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID_Followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile2', to='main.Profile')),
                ('UserID_Following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile1', to='main.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(default='', max_length=1000)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile')),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Post')),
            ],
        ),
    ]
