# Generated by Django 3.0.2 on 2020-02-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Run',
        ),
    ]
