# Generated by Django 3.0.3 on 2020-02-24 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_type',
        ),
    ]
