# Generated by Django 3.0.3 on 2020-02-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_profile_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Following',
        ),
    ]
