# Generated by Django 3.0.2 on 2020-02-25 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200225_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='run_id',
        ),
    ]
