# Generated by Django 3.0.3 on 2020-02-28 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200226_1825'),
        ('main', '0004_auto_20200228_2144'),
    ]

    operations = [
    ]
