# Generated by Django 3.0.2 on 2020-03-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200302_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_mileage',
            field=models.FloatField(default=0.0),
        ),
    ]
