# Generated by Django 3.0.3 on 2020-03-09 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200307_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Write something about your run here! Max 1000 characters.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='distance',
            field=models.FloatField(default=0.0, help_text='Enter distance in miles.', validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.TextField(default='', help_text='Where did you run? Max 100 characters.', max_length=100),
        ),
    ]
